using System.Globalization;
using System.Text;

namespace TimeTracker
{
    public static class ReportGenerator
    {
        public static string GenerateHtmlReport(DateTime start, DateTime end, DatabaseManager db)
        {
            var top = db.GetTopProcesses(start, end);
            var cats = db.GetStatsByCategory(start, end);
            var totalMs = top.Sum(t => t.TotalUsage);
            var ts = TimeSpan.FromMilliseconds(totalMs);

            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width'>");
            sb.AppendLine("<style>body{font-family:Segoe UI,sans-serif;max-width:700px;margin:40px auto;color:#1a1d2e;background:#f5f6fa} ");
            sb.AppendLine("h1{color:#6c5ce7}h2{margin-top:24px}table{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.05)}");
            sb.AppendLine("th{background:#6c5ce7;color:#fff;padding:12px 16px;text-align:left}td{padding:10px 16px;border-bottom:1px solid #e5e7eb}");
            sb.AppendLine(".summary{background:#fff;padding:24px;border-radius:12px;box-shadow:0 2px 8px rgba(0,0,0,.05)}");
            sb.AppendLine(".badge{background:#f3f4f6;padding:4px 12px;border-radius:20px;font-size:12px}</style></head><body>");

            sb.AppendLine(CultureInfo.InvariantCulture, $"<h1>📊 TimeTracker 使用报告</h1>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<p>{start:yyyy-MM-dd} ~ {end:yyyy-MM-dd}</p>");
            sb.AppendLine("<div class='summary'>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<p><strong>总使用时长:</strong> {(int)ts.TotalHours}h {ts.Minutes}m</p>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<p><strong>追踪应用数:</strong> {top.Count}</p>");
            sb.AppendLine("</div>");

            // Top 10
            sb.AppendLine("<h2>Top 10 应用</h2><table><tr><th>应用</th><th>用时</th></tr>");
            foreach (var t in top.Take(10))
            {
                var d = TimeSpan.FromMilliseconds(t.TotalUsage);
                sb.AppendLine(CultureInfo.InvariantCulture, $"<tr><td>{t.ProcessName}</td><td>{(int)d.TotalHours}h {d.Minutes}m</td></tr>");
            }
            sb.AppendLine("</table>");

            // 分类
            sb.AppendLine("<h2>按标签分类</h2><table><tr><th>分类</th><th>用时</th></tr>");
            foreach (var c in cats.Take(10))
            {
                var d = TimeSpan.FromMilliseconds(c.TotalUsage);
                sb.AppendLine(CultureInfo.InvariantCulture, $"<tr><td>{c.CategoryName}</td><td>{(int)d.TotalHours}h {d.Minutes}m</td></tr>");
            }
            sb.AppendLine("</table>");

            sb.AppendLine(CultureInfo.InvariantCulture, $"<p style='color:#9ca3af;margin-top:32px'>Generated by TimeTracker</p>");
            sb.AppendLine("</body></html>");
            return sb.ToString();
        }
    }
}
